version: '2'
services:
  data:
    container_name: demo_data
    build: ./data
    volumes:
      - .:/www
    command: /var/local/entrypoint.sh

  db:
    container_name: demo_mysql
    build: ./mysql
    ports:
      - "3309:3309"
    volumes:
      - .docker_data/mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
      MYSQL_USER: demo
      MYSQL_PASSWORD: demo
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  php:
    container_name: demo_php
    build: ./php
    volumes_from:
      - data
    links:
      - db
    environment:
      CACHE_DIR: /www/var/cache
      LOG_DIR: /www/var/logs
      SESSION_DIR: /www/var/sessions
      MYSQL_PASSWORD: demo
      MYSQL_DATABASE: demo
      MYSQL_USER: demo
      MYSQL_HOST: demo_mysql
    command: /var/local/entrypoint.sh

  nginx:
    container_name: demo_nginx
    build:
      context: ./nginx
    ports:
      - "8001:80"
    links:
      - php
    volumes_from:
      - php
      - data
